module.exports = {
  GetAllUsers: require('./GetAllUsers'),
  CreateUser: require('./CreateUser'),
  GetUser: require('./GetUser'),
  UpdateUser: require('./UpdateUser'),
  DeleteUser: require('./DeleteUser'),
  SignupUser: require('./SignupUser'),
  GetProfile: require('./GetProfile'),
  UserLogin: require('./UserLogin'),
  UserChangePassword: require('./UserChangePassword'),
  UserUpdateProfile: require('./UserUpdateProfile'),
  UpdateProfileById: require('./UpdateProfileById'),
  GetSchoolList: require('./GetSchoolList'),
  GetCustomUser: require('./GetCustomUser'),
  CheckUser: require('./CheckUser'),
};